// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Complete():Promise<void>;

export function Dismiss():Promise<void>;

export function GetAccentColor():Promise<string>;

export function GetBrand():Promise<app.BrandInfo>;

export function GetCheckState():Promise<Record<string, boolean>>;

export function GetFinalHTML():Promise<string>;

export function GetHelpURL():Promise<string>;

export function GetPageHTML(arg1:number):Promise<string>;

export function GetPages():Promise<Array<app.PageInfo>>;

export function GetTheme():Promise<string>;

export function GetUsername():Promise<string>;

export function OpenHelp():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function Ready():Promise<void>;

export function ToggleCheckItem(arg1:string):Promise<boolean>;
