// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Complete() {
  return window['go']['app']['App']['Complete']();
}

export function Dismiss() {
  return window['go']['app']['App']['Dismiss']();
}

export function GetAccentColor() {
  return window['go']['app']['App']['GetAccentColor']();
}

export function GetBrand() {
  return window['go']['app']['App']['GetBrand']();
}

export function GetCheckState() {
  return window['go']['app']['App']['GetCheckState']();
}

export function GetFinalHTML() {
  return window['go']['app']['App']['GetFinalHTML']();
}

export function GetHelpURL() {
  return window['go']['app']['App']['GetHelpURL']();
}

export function GetPageHTML(arg1) {
  return window['go']['app']['App']['GetPageHTML'](arg1);
}

export function GetPages() {
  return window['go']['app']['App']['GetPages']();
}

export function GetTheme() {
  return window['go']['app']['App']['GetTheme']();
}

export function GetUsername() {
  return window['go']['app']['App']['GetUsername']();
}

export function OpenHelp() {
  return window['go']['app']['App']['OpenHelp']();
}

export function OpenURL(arg1) {
  return window['go']['app']['App']['OpenURL'](arg1);
}

export function Ready() {
  return window['go']['app']['App']['Ready']();
}

export function ToggleCheckItem(arg1) {
  return window['go']['app']['App']['ToggleCheckItem'](arg1);
}
